license="MIT"

modLoader="javafml"

loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

[[mods]] #mandatory

modId="easywhitelist"

version="1.0.2"

displayName="EasyWhitelistMod"
updateJSONURL=""
displayURL=""
displayTest="IGNORE_SERVER_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

logoFile=""

credits="nikitacartez,kaiserproger(porting to Forge 1.19.2)"

authors="nikitacartez,kaiserproger"
# The description text for the mod (multi line!) (#mandatory)
description='''
A mod that make whitelist name-based instead of uuid-based
'''